Repository dictyBase/dicty-graphql-schema, pull requests merged in 2021-11, with the labels that each got.

#42 Create listOfPublications.graphql
  src/queries/listOfPublications.graphql
Labels: size/S

#51 Add Default Value of 4 to ListRecentPublication
  src/queries/publication.graphql
Labels: size/XS

#54 ci(Mergify): configuration update
  .mergify.yml
Labels: size/S

#71 Feature/gene-strains-column
  .yarn/releases/yarn-3.1.1.cjs
  .yarn/releases/yarn-berry.cjs
  .yarnrc.yml
  dist/index.js
  package.json
  src/queries/gene.graphql
  src/schema/gene.graphql
  types/index.ts
  yarn.lock
Labels: size/XXL

#74 build: run 'yarn run compile' due to new package updates
  dist/index.js
  types/index.ts
Labels: size/L
